openapi: 3.1.0
info:
  title: RAG Assistant API
  version: 1.0.0
  description: 사용자의 요청에 따라 문서를 수집하고 검색하는 RAG 기반 API
servers:
  - url: https://rag-ai-assistrant.onrender.com
paths:
  /start_data_ingestion:
    post:
      operationId: startDataIngestion
      summary: 웹사이트 문서 수집 및 벡터화
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site_url:
                  type: string
                  description: 문서를 수집할 대상 사이트 URL
              required:
                - site_url
      responses:
        "200":
          description: 수집 및 임베딩 완료 메시지
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /ask:
    post:
      operationId: askQuestion
      summary: 문서 기반 질문 응답
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: 사용자의 질문
              required:
                - query
      responses:
        "200":
          description: 관련 문서 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      type: string
                    description: 관련 문서 chunk 리스트
