openapi: 3.1.0
info:
  title: RAG Assistant API
  version: 1.0.0
  description: 문서를 자동으로 수집하고 질문에 답하는 RAG 기반 AI 비서 API입니다.

servers:
  - url: https://rag-ai-assistrant.onrender.com

paths:
  /start_data_ingestion:
    post:
      operationId: startDataIngestion
      summary: 문서 자동 수집 및 임베딩
      description: 주어진 사이트 URL로부터 문서를 수집하고 벡터 DB에 반영합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                site_url:
                  type: string
                  description: 크롤링할 시작 사이트 URL
              required:
                - site_url
      responses:
        '200':
          description: 처리 완료 메시지
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /health:
    get:
      operationId: checkHealth
      summary: 서버 상태 점검
      description: 서버가 정상 작동 중인지 확인합니다.
      responses:
        '200':
          description: 정상 상태
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
